name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.3.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  http: ^0.13.3
  http_parser: ^4.0.0
  logging: ^1.0.1
  sync: ^0.3.0

dev_dependencies:
  test: ^1.17.11
